# Generated by Django 4.0.2 on 2022-02-25 20:57

import archive.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=64, unique=True, verbose_name='产品名称')),
                ('product_code', models.CharField(blank=True, max_length=32, unique=True, verbose_name='产品代码')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='产品说明')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
            },
        ),
        migrations.CreateModel(
            name='StageType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_id', models.IntegerField(default=1, verbose_name='发放代码')),
                ('stage_name', models.CharField(max_length=16, unique=True, verbose_name='发放类型')),
                ('stage_mark', models.CharField(max_length=16, verbose_name='发放标记')),
                ('remark', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '发放类型',
                'verbose_name_plural': '发放类型',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('archive_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archive_no', models.CharField(max_length=18, verbose_name='文件发放单号')),
                ('description', models.CharField(max_length=256, verbose_name='发放说明')),
                ('username', models.CharField(max_length=30, verbose_name='发放人')),
                ('file', models.FileField(blank=True, max_length=255, upload_to=archive.models.upload_to, verbose_name='发放文件')),
                ('bom', models.FileField(blank=True, max_length=255, upload_to=archive.models.upload_to, verbose_name='发放清单')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发放时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.product', verbose_name='产品名称')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.stagetype', verbose_name='发放类型')),
            ],
            options={
                'verbose_name': '文档发放信息',
                'verbose_name_plural': '文档发放信息',
            },
        ),
    ]
