# Generated by Django 4.0.2 on 2022-02-25 20:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent', models.CharField(max_length=32, null=True, verbose_name='父项编码')),
                ('archive', models.CharField(max_length=64, null=True, verbose_name='发放单号')),
                ('sn', models.CharField(max_length=32, verbose_name='序号')),
                ('draw', models.CharField(max_length=50, null=True, verbose_name='图号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('before_code', models.CharField(max_length=60, null=True, verbose_name='更改前编码')),
                ('after_code', models.CharField(max_length=60, null=True, verbose_name='更改后编码')),
                ('before_description', models.CharField(max_length=60, null=True, verbose_name='更改前说明')),
                ('after_description', models.CharField(max_length=60, null=True, verbose_name='更改后说明')),
                ('change_type', models.IntegerField(default=2, verbose_name='更改类别')),
                ('change_draw', models.CharField(max_length=20, null=True, verbose_name='更改方式')),
                ('stock', models.IntegerField(null=True, verbose_name='库存')),
                ('on_order', models.IntegerField(null=True, verbose_name='在制')),
                ('suggestion', models.CharField(max_length=50, null=True, verbose_name='处理建议')),
                ('product', models.CharField(max_length=50, null=True, verbose_name='涉及产品')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设计更改清单',
                'verbose_name_plural': '设计更改清单',
            },
        ),
        migrations.CreateModel(
            name='PartCost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, null=True, verbose_name='编码')),
                ('material_cost', models.FloatField(default=0, max_length=8, verbose_name='材料成本')),
                ('labor_cost', models.FloatField(default=0, max_length=8, verbose_name='人工成本')),
                ('managed_cost', models.FloatField(default=0, max_length=8, verbose_name='管理成本')),
                ('cost', models.FloatField(default=0, max_length=8, verbose_name='单件成本')),
                ('source', models.CharField(default='导入', max_length=20, verbose_name='成本来源')),
                ('cost_valid', models.IntegerField(default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '成本库',
                'verbose_name_plural': '成本库',
            },
        ),
        migrations.CreateModel(
            name='PartCode',
            fields=[
                ('code', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True, verbose_name='编码')),
                ('draw', models.CharField(blank=True, max_length=50, null=True, verbose_name='图号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='材料')),
                ('weight', models.FloatField(blank=True, max_length=6, null=True, verbose_name='重量')),
                ('remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='备注')),
                ('division', models.CharField(blank=True, max_length=20, null=True, verbose_name='分工')),
                ('part_valid', models.IntegerField(default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='时间')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.ssfile', verbose_name='图纸')),
            ],
            options={
                'verbose_name': '物料库',
                'verbose_name_plural': '物料库',
            },
        ),
        migrations.CreateModel(
            name='ErpBom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(max_length=32, verbose_name='序列号')),
                ('archive', models.CharField(max_length=64, verbose_name='产品代码')),
                ('parent', models.CharField(max_length=64, verbose_name='父项编码')),
                ('quantity', models.FloatField(max_length=4, verbose_name='数量')),
                ('remark', models.CharField(max_length=50, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.partcode', verbose_name='子件编码')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.stagetype', verbose_name='发放类型')),
            ],
            options={
                'verbose_name': '导入的ERP-BOM',
                'verbose_name_plural': '导入的ERP-BOM',
            },
        ),
        migrations.CreateModel(
            name='ArchiveBom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(max_length=32, verbose_name='序列号')),
                ('archive', models.CharField(max_length=64, null=True, verbose_name='发放单号')),
                ('parent', models.CharField(max_length=32, null=True, verbose_name='父项编码')),
                ('quantity', models.FloatField(max_length=4, verbose_name='数量')),
                ('remark', models.CharField(max_length=50, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.partcode', verbose_name='子件编码')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.stagetype', verbose_name='发放类型')),
            ],
            options={
                'verbose_name': '物料发放BOM',
                'verbose_name_plural': '物料发放BOM',
            },
        ),
        migrations.CreateModel(
            name='CurrentBom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent', models.CharField(max_length=32, null=True, verbose_name='父项编码')),
                ('quantity', models.FloatField(max_length=4, verbose_name='数量')),
                ('sort_key', models.IntegerField(null=True, verbose_name='排序号')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='parts.partcode', verbose_name='子件编码')),
            ],
            options={
                'verbose_name': '当前BOM',
                'verbose_name_plural': '当前BOM',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
