# Generated by Django 4.0.2 on 2022-02-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivebom',
            name='bom_valid',
            field=models.IntegerField(default=1, verbose_name='Bom状态'),
        ),
        migrations.AddField(
            model_name='archivebom',
            name='valid_info',
            field=models.CharField(max_length=128, null=True, verbose_name='失效单号'),
        ),
        migrations.AddField(
            model_name='archivebom',
            name='valid_time',
            field=models.DateTimeField(null=True, verbose_name='失效时间'),
        ),
        migrations.AddField(
            model_name='erpbom',
            name='bom_valid',
            field=models.IntegerField(default=1, verbose_name='Bom状态'),
        ),
        migrations.AddField(
            model_name='erpbom',
            name='valid_info',
            field=models.CharField(max_length=128, null=True, verbose_name='失效单号'),
        ),
        migrations.AddField(
            model_name='erpbom',
            name='valid_time',
            field=models.DateTimeField(null=True, verbose_name='失效时间'),
        ),
        migrations.AddField(
            model_name='partcode',
            name='valid_time',
            field=models.DateTimeField(null=True, verbose_name='失效时间'),
        ),
        migrations.AddField(
            model_name='partcost',
            name='valid_time',
            field=models.DateTimeField(null=True, verbose_name='失效时间'),
        ),
    ]
