# Generated by Django 3.2.6 on 2022-02-17 20:44

import datetime
from django.db import migrations, models
import django.utils.timezone
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=12, verbose_name='文件编号')),
                ('filename', models.CharField(blank=True, max_length=30, verbose_name='文件名称')),
                ('type', models.CharField(default='下载', max_length=8, verbose_name='操作类型')),
                ('username', models.CharField(max_length=30, verbose_name='操作用户')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '文档操作记录',
                'verbose_name_plural': '文档操作记录',
            },
        ),
        migrations.CreateModel(
            name='ssFile',
            fields=[
                ('file_id', models.IntegerField(default=files.models.createfileno, primary_key=True, serialize=False, unique=True, verbose_name='文件编号')),
                ('filename', models.CharField(max_length=64, verbose_name='图号')),
                ('stage', models.IntegerField(choices=[(1, 'test'), (5, '一次性'), (10, '试制'), (20, '实验'), (30, '小批'), (100, '设计更改')], default=10, verbose_name='发放类型')),
                ('product', models.CharField(default='未分类', max_length=32, verbose_name='产品名称')),
                ('archive', models.CharField(max_length=64, null=True, verbose_name='发放单号')),
                ('output', models.CharField(blank=True, max_length=20, null=True, verbose_name='发放部门')),
                ('file_valid', models.IntegerField(default=1, verbose_name='图纸状态')),
                ('valid_info', models.CharField(blank=True, max_length=128, null=True, verbose_name='状态说明')),
                ('valid_time', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('original_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='原始物料')),
                ('username', models.CharField(max_length=30, verbose_name='设计')),
                ('filepath', models.FileField(max_length=255, upload_to=files.models.upload_to, verbose_name='文件位置')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发放时间')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'permissions': (('download_ssfile', '可以下载文件'),),
            },
        ),
    ]
